### PR TITLE
Add binder badge

### PR DESCRIPTION
**Pull request by ceball**
The button will say "launch binder". 

I put it in a note (https://docutils.sourceforge.io/docs/ref/rst/directives.html#note). I don't know how this will look with our theme, or where's best to put it. I hope it does not take up much vertical space.

Add `--binder=top` to `nbsite generate-rst` to add above the title. Maybe should have an option for below title instead?

If it looks ok, in future could change the nblink option to some kind of similar thing (rather than being separated by a horizontal rule as now), or combine the two (binder, github notes) into one. 

(Or maybe have generic preamble option, which defaults to these kinds of things, but can be overridden in config...)

### CODE REVIEW

**Comment by ceball** [comment]
I've asked for reviews but it might be better if I just make a dev release and you see how it looks when used for sites (and make changes in a new PR if you see improvements). So maybe just say if you have a strong opinion about not doing it this way, or you see some problem...

**Comment by ceball** [comment]
P. S. I only did this to say thanks to Philipp for writing a panel 0.10 blog post 😂

**Comment by jbednar** [comment]
Looks great to me!

**Comment by philippjfr** [comment]
Great, thanks so much! Will take a look at the output in the morning.

**Pull request merged**
